/**
 * ============================================================================
 * CSS BUNDLER (build-css.js)
 * ============================================================================
 * Reads src/css/index.css's @import chain and concatenates every file it
 * references, in the same order, into one file: src/css/bundle.css. Each
 * file's content is wrapped in the same @layer block its @import already
 * declared, so the bundle preserves CUBE CSS's cascade-layer ordering
 * exactly - this is a request-count fix, not a rewrite of how the cascade
 * works.
 *
 * index.css itself is untouched and stays the source of truth for adding/
 * reordering imports during development (26 separate requests, all
 * render-blocking, is fine for local editing where caching does the work).
 * The bundle is what production HTML actually links to.
 *
 * DO NOT hand-edit bundle.css — it is regenerated every time this runs.
 * Edit index.css (or the individual files it imports) instead, then:
 *
 *   npm run build:css
 * ============================================================================
 */

const fs = require("fs");
const path = require("path");

const CSS_ROOT = path.join(__dirname, "src", "css");
const ENTRY_PATH = path.join(CSS_ROOT, "index.css");
const OUTPUT_PATH = path.join(CSS_ROOT, "bundle.css");

const IMPORT_PATTERN =
  /@import\s+url\(["']([^"']+)["']\)\s+layer\((\w+)\);/g;

// Matches url("./relative") / url('../relative') — deliberately excludes
// http(s):, data:, and absolute paths, none of which need rewriting.
const RELATIVE_URL_PATTERN = /url\((["'])(\.\.?\/[^"']+)\1\)/g;

/**
 * A file's own relative url()s (e.g. font-faces.css pointing at
 * ../../../assets/fonts/x.woff2) are correct relative to THAT file's
 * location, which is exactly what makes them work during dev when index.css
 * is read via its real @import chain. Once flattened into one bundle sitting
 * directly in CSS_ROOT, the same relative path resolves from the wrong
 * directory — so every relative url() gets re-expressed relative to
 * CSS_ROOT (where bundle.css itself lives) as part of bundling.
 */
function rewriteRelativeUrls(content, fileDir) {
  return content.replace(RELATIVE_URL_PATTERN, (match, quote, relativeUrl) => {
    const absoluteTarget = path.resolve(fileDir, relativeUrl);
    const rewritten = path
      .relative(CSS_ROOT, absoluteTarget)
      .split(path.sep)
      .join("/");
    return `url(${quote}${rewritten}${quote})`;
  });
}

function build() {
  const entry = fs.readFileSync(ENTRY_PATH, "utf8");

  const layerOrderMatch = entry.match(/@layer\s+[\w,\s]+;/);
  const layerOrder = layerOrderMatch ? layerOrderMatch[0] : "";

  const imports = [...entry.matchAll(IMPORT_PATTERN)];
  if (imports.length === 0) {
    throw new Error(
      "[build-css] no @import statements found in index.css - is the pattern still url(...) layer(...)?",
    );
  }

  const sections = imports.map(([, relativePath, layerName]) => {
    const filePath = path.join(CSS_ROOT, relativePath);
    const rawContent = fs.readFileSync(filePath, "utf8").trim();
    const content = rewriteRelativeUrls(rawContent, path.dirname(filePath));
    return `@layer ${layerName} {\n${content}\n}`;
  });

  const output =
    `/**\n` +
    ` * AUTO-GENERATED by build-css.js from index.css's @import chain.\n` +
    ` * Do not edit this file directly — your changes will be overwritten.\n` +
    ` * Edit index.css or the files it imports, then run: npm run build:css\n` +
    ` */\n\n` +
    `${layerOrder}\n\n` +
    `${sections.join("\n\n")}\n`;

  fs.writeFileSync(OUTPUT_PATH, output, "utf8");

  console.log(
    `[build-css] wrote ${path.relative(__dirname, OUTPUT_PATH)} (${imports.length} files bundled)`,
  );
}

build();
