/**
 * ============================================================================
 * CSS BUNDLER (build-css.js)
 * ============================================================================
 * Reads each entry file's @import chain and concatenates every file it
 * references, in the same order, into one output file. Each file's content
 * is wrapped in the same @layer block its @import already declared, so the
 * bundle preserves CUBE CSS's cascade-layer ordering exactly - this is a
 * request-count fix, not a rewrite of how the cascade works.
 *
 * index.css (the full "everything" chain — still what 404.html links to,
 * and still the easiest single file to skim the whole cascade from during
 * local dev) and src/css/entries/*.css (one per production page, importing
 * only the blocks that page's DOM actually renders — see each file's own
 * header for the audit behind its specific list) are all untouched by this
 * script and stay the source of truth for adding/reordering imports. The
 * bundles are what production HTML actually links to.
 *
 * DO NOT hand-edit any *bundle.css — they are regenerated every time this
 * runs. Edit an entry file (or the individual files it imports) instead,
 * then:
 *
 *   npm run build:css
 * ============================================================================
 */

const fs = require("fs");
const path = require("path");

const CSS_ROOT = path.join(__dirname, "src", "css");

// One entry -> output pair per bundle. Add a row here for any new page
// that needs its own page-specific CSS entry.
const BUILDS = [
  { entry: "index.css", output: "bundle.css" },
  { entry: "entries/home.css", output: "home-bundle.css" },
  { entry: "entries/classroom.css", output: "classroom-bundle.css" },
  { entry: "entries/practice.css", output: "practice-bundle.css" },
];

const IMPORT_PATTERN =
  /@import\s+url\(["']([^"']+)["']\)\s+layer\((\w+)\);/g;

// Matches url("./relative") / url('../relative') — deliberately excludes
// http(s):, data:, and absolute paths, none of which need rewriting.
const RELATIVE_URL_PATTERN = /url\((["'])(\.\.?\/[^"']+)\1\)/g;

/**
 * A file's own relative url()s (e.g. font-faces.css pointing at
 * ../../../assets/fonts/x.woff2) are correct relative to THAT file's
 * location, which is exactly what makes them work during dev when index.css
 * is read via its real @import chain. Once flattened into one bundle sitting
 * directly in CSS_ROOT, the same relative path resolves from the wrong
 * directory — so every relative url() gets re-expressed relative to
 * CSS_ROOT (where bundle.css itself lives) as part of bundling.
 */
function rewriteRelativeUrls(content, fileDir) {
  return content.replace(RELATIVE_URL_PATTERN, (match, quote, relativeUrl) => {
    const absoluteTarget = path.resolve(fileDir, relativeUrl);
    const rewritten = path
      .relative(CSS_ROOT, absoluteTarget)
      .split(path.sep)
      .join("/");
    return `url(${quote}${rewritten}${quote})`;
  });
}

function build(entryRelativePath, outputRelativePath) {
  const entryPath = path.join(CSS_ROOT, entryRelativePath);
  const outputPath = path.join(CSS_ROOT, outputRelativePath);
  const entry = fs.readFileSync(entryPath, "utf8");

  const layerOrderMatch = entry.match(/@layer\s+[\w,\s]+;/);
  const layerOrder = layerOrderMatch ? layerOrderMatch[0] : "";

  const imports = [...entry.matchAll(IMPORT_PATTERN)];
  if (imports.length === 0) {
    throw new Error(
      `[build-css] no @import statements found in ${entryRelativePath} - is the pattern still url(...) layer(...)?`,
    );
  }

  // Resolved relative to the entry file's own directory, not always
  // CSS_ROOT — entries/*.css sit one level deeper than index.css, so their
  // "../blocks/x.css" imports need that extra level accounted for.
  const sections = imports.map(([, relativePath, layerName]) => {
    const filePath = path.resolve(path.dirname(entryPath), relativePath);
    const rawContent = fs.readFileSync(filePath, "utf8").trim();
    const content = rewriteRelativeUrls(rawContent, path.dirname(filePath));
    return `@layer ${layerName} {\n${content}\n}`;
  });

  const output =
    `/**\n` +
    ` * AUTO-GENERATED by build-css.js from ${entryRelativePath}'s @import chain.\n` +
    ` * Do not edit this file directly — your changes will be overwritten.\n` +
    ` * Edit ${entryRelativePath} or the files it imports, then run: npm run build:css\n` +
    ` */\n\n` +
    `${layerOrder}\n\n` +
    `${sections.join("\n\n")}\n`;

  fs.writeFileSync(outputPath, output, "utf8");

  console.log(
    `[build-css] wrote ${path.relative(__dirname, outputPath)} (${imports.length} files bundled)`,
  );
}

for (const { entry, output } of BUILDS) {
  build(entry, output);
}
